### PR TITLE
Feature/update pypi (#39)

### PR DESCRIPTION
**Pull request by hardikvasa**
* chg: doc: license on setup.py

* chg: doc: rename README.md to README.rst

* chg: doc: syntax from markdown to rst

* chg: doc: command on readme

* chg: doc: re add table

* chg: doc: remove duplicate example

* chg: doc: remove readme convertion

rst is already default readme filetype

* chg: doc: update table to latest upstream commit

* chg: doc: update classifiers to latest upstream commit

* chg: dev: update print_urls description

### CODE REVIEW

**Comment by hardikvasa** [comment]
@rachmadaniHaryono i did not originally intend to merge your PR in stage, but I am just testing this new branch and so I thought of merging your PR in stage and then merge it with master. :)

**Comment by rachmadaniHaryono** [comment]
actually #39 is not finished yet, there is some update and change that you have to know (or change).

although i will still create another pr to update that.

**Comment by hardikvasa** [comment]
@rachmadaniHaryono my bad, sorry. Okay...you can create a PR for master with the remaining changes!

readme.rst required for pypi since it cannot take readme.md right?

**Comment by rachmadaniHaryono** [comment]
it is possible with using markdown, but it require pypandoc and the result may not as intended

https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work

**Comment by hardikvasa** [comment]
gotcha! thanks for the reference.

**Pull request merged**
