### PR TITLE
added offset-option to specify the start index

### PR DESCRIPTION
**Pull request by leberknecht**
added `--offset` or short `-of` option to skip a number of links before starting to download

### CODE REVIEW

**Comment by GioPat** [comment]
I think you need to update also the readme! :)
I did it in my commit because I added an attribute

**Comment by leberknecht** [comment]
Uh, indeed. Added :)

**Comment by hardikvasa** [comment]
@leberknecht thanks for the feature 😊 

Wouldn't this break if no offset is mentioned? it will always go into the `elif int(arguments['offset']) > count` and look for offset argument which if it will not find, will consider it as NoneType and break.

I think it should be something like this:

```
elif arguments['offset'] and count < int(arguments['offset']):
    count += 1
    page = page[end_content:]
```

do let me know if this makes sense...

**Comment by hardikvasa** [comment]
@leberknecht did you have a chance to go through the above comment?

**Comment by hardikvasa** [comment]
Closing this PR since the code breaks when there is no -of param. Fixed it and pushed the code but credited you on the PR. Thanks for this nice feature! :)

**Pull request closed without merging**
