### PR TITLE
fix: dev: ImportError on python2

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
simple fix for `ImportError` on python2

this also enable module to be run directly. e.g. `python -m google_images_download -k 'red picture`

related #41

### CODE REVIEW

**Comment by hardikvasa** [comment]
Changes are merged. Thanks!

**Comment by rachmadaniHaryono** [comment]
based on your description, the code look like this
```python
class GoogleImagesDownload():
    ...
if __name__ = '__main__':
    gid = GoogleImagesDownload()
    gid.run()
    ...
```
if it is like that just move the code under `if __name__ = '__main__'` to main function.

```python
class GoogleImagesDownload():
    ...
def main():
    gid = GoogleImagesDownload()
    gid.run()
    ...
if __name__ = '__main__':
    main()
```
if the main function already on `googleimagesdownload.py` file, you can set up console script entry point like below:
```python
entry_points={
        'console_scripts': [
            'googleimagesdownload = google_images_download.googleimagesdownload:main'
            ]}
```

**Comment by hardikvasa** [comment]
@rachmadaniHaryono thanks for your quick response.

so just to clarify the pseudo code looks like below:

```
class GoogleImagesDownload():
    ...
    # class ends here

def main():
    gid = GoogleImagesDownload()
    gid.run()
    ...
if __name__ = '__main__':
    main()
```

then doesn't the entry point `google_images_download.googleimagesdownload:main` suggest that the main function is inside the class `googleimagesdownload` ? 

shouldn't it be `google_images_download.google_images_download:main` ? <directory>.<file>:<mainFunction> ?

**Comment by rachmadaniHaryono** [comment]
it is my mistake. what you are suggesting is correct

`google_images_download.google_images_download:main`

>then doesn't the entry point google_images_download.googleimagesdownload:main suggest that the main function is inside the class googleimagesdownload ?

i forget filename is `google_images_download` instead of `googleimagesdownload`. i will edit my comment above

just as note if you want to set entry point on specific class static method you can set it up like this
```python
entry_points={
        'console_scripts': [
            'func1 = google_images_download.googleimagesdownload:GoogleImagesDownload.func1'
        ]}
```

**Comment by hardikvasa** [comment]
@rachmadaniHaryono Great! thanks for clarifying that. Much help :-)

**Pull request merged**
