### PR TITLE
Pip pakage

### PR DESCRIPTION
**Pull request by psuzn**
Created a pip pakage named google_images_download
https://pypi.python.org/pypi/google-images-download

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
update here

https://pypi.python.org/pypi/google-images-download/1.0.1

if this pr accepted the readme should be changed.

also if possible convert it directly to rst, so no conversion is needed when upload it to pypi

**Comment by hardikvasa** [comment]
[pasting it her instead]
@psuzn thanks a lot for the PR. Great work on creating the PIP package. I will soon get some free time and I will merge this PR in mainline.
Can you also give me access to the pip package? my username is **hnvasa**

@rachmadaniHaryono do let me know if there are any changes to be made post merge... :)

**Comment by rachmadaniHaryono** [comment]
@hardikvasa 

>just wanted to ask why is the BSD license attached to the PIP package if the original repo is under MIT?

It should be changed on setup.py. I can create pr for that along some edit to Readme file.

>do let me know if there are any changes to be made post merge

- removing emoji
- converting it to rst 
- change command line guide

This can be made after this pr merged

**Comment by hardikvasa** [comment]
thanks @rachmadaniHaryono . Merged the PR.

**Pull request merged**
