### PR TITLE
Skip images with certain urls

### PR DESCRIPTION
**Pull request by crainbows**
The ability to skip images with urls that match certain sites has been discussed in issues #201 and #187. 
This pull request adds an argument that will ignore images where the url matches anything within the provided delimited array.

### CODE REVIEW

**Comment by hardikvasa** [comment]
this is a nice little add on. I will test this feature out in local.

**Comment by hardikvasa** [comment]
@Crainbows this update does not work as intended.

When -iu is not present in the command, it gives me the error
`AttributeError: 'bool' object has no attribute 'split'`

This is most likely because you are not validating if ignore_urls is set.

Now when i give -iu with the following command:
`python3 google_images_download.py -k baloons -l 5 -iu 'amazon.com' -p`

in the terminal, it says image ignored for all images even when it downloads some of the images. This is most because you are returning the status of the image as `success` instead of `fail`

can you correct the changes and update the PR?

**Comment by Crainbows** [comment]
@hardikvasa thanks for checking it out. Those issues should be addressed in the latest commit 72cdf35.

**Comment by hardikvasa** [comment]
@Crainbows thanks for the update. Unfortunately when you added another commit, the file still had some conflicts. But I did not mention it then because some new updates were coming to this library. Now since those updates are done, can you pull all the latest changes and create a fresh new commit?

I look forward to it.

**Pull request merged**
