### PR TITLE
Adding the ability to download from specific google image URL 

### PR DESCRIPTION
**Pull request by a0m0rajab**

### CODE REVIEW

**Comment by hardikvasa** [comment]
Awesome! thanks for the PR. I will test this for compatibility and then merge it.

**Comment by hardikvasa** [comment]
the script however breaks since the entire page does not need to be downloaded in search for links...i have sent merged another PR to fix it

**Comment by a0m0rajab** [comment]
The script was not mean to download a single image , sometimes when you search at google you can search by image and you dont know what "keywords" to use to find this image so you just got the google search link , i wanted to have the ability to download images from that page  , 

it would be helpful for "
search by image and view more features ,

**Comment by hardikvasa** [comment]
Ahh i see...my bad. So this is similar to clicking "Search by images" and downloading similar images?

Can you give me an example google link/url that you will put in the script?

**Comment by a0m0rajab** [comment]
you can see here image labeled as twitter , did not lead to twitter logo pictures : 

https://www.google.com.tr/search?sa=G&hl=en-TR&tbs=simg:CAEStAIJfTJt0F80NiAaqAILEKjU2AQaBAgVCAQMCxCwjKcIGmIKYAgDEijNFdwDzxXSFvUKowPMFYce4Av4Cok53jncOacqrSrVKdE4_1zipKvIqGjAgNC9Cu1ugW8rL0i84g9H8SCUXYSMzTXB2FxVZL_1dsexVSkrfJhYJHjwZq3Nqt6e4gBAwLEI6u_1ggaCgoICAESBMBKQtgMCxCd7cEJGpMBChgKBm5hdHVyZdqliPYDCgoIL20vMDVoMG4KJQoRbmF0dXJhbCBsYW5kc2NhcGXapYj2AwwKCi9tLzAzZDI4eTMKGAoFZ3Jhc3PapYj2AwsKCS9tLzA4dDljXwodCgpydXJhbCBhcmVh2qWI9gMLCgkvbS8wMWY0dGQKFwoFd2F0ZXLapYj2AwoKCC9tLzA4MzhmDA&q=Twitter&tbm=isch&ved=0ahUKEwjUhrG7hovZAhVE2KQKHSYTCRsQsw4INg

**Pull request merged**
