### PR TITLE
Fixes for some errors: letter 'ś' and BadStatusLine error

### PR DESCRIPTION
**Pull request by piotrex**
some fixes or workarounds for some errors. I needed these edits for letter 'ś' work properly and handle BadStatusLine error catch.

### CODE REVIEW

**Comment by piotrex** [comment]
see #113

**Comment by piotrex** [comment]
dont know if it good aproach but it works for me.

**Comment by jimgros** [comment]
I used your code on searches that had previously issued a BadStatusLine error, and it solved the issue for me as well. Thanks!

**Comment by hardikvasa** [comment]
@piotrex @jimgros 

thanks for pointing out this bug. Can one of answer the below questions?
* Example of one or two keywords that leads to BadStatusLine
* What is the python version you are using
* Can you paste the complete error message that you have received?

I wanted to at the very least reproduce this error before merging this change. By just using 'ś' in a keyword does not lead me to the said error. Thanks.

**Comment by hardikvasa** [comment]
@piotrex thanks for the PR update. For now adding exception for BadStatusLine will help identify and catch the errors. Merged the PR.

**Pull request merged**
